### ISSUE TITLE
handling paged event table

### ISSUE THREAD

**Issue by dpaczewski** [tobilg/facebook-events-by-location-core#12]
Hi.

I was checking the following venue: ProgresjaMusicZone?fields=events

When you look at the returned output you can see:

>     "paging": {
>      "cursors": {
>        "before": "OTM4NzAzMjI2MjY1NTM2",
>        "after": "MTI0ODM3NzE0NTI1NjY0MwZDZD"
>      },
>      "next": "https://graph.facebook.com/v2.9/142450042462794/events?access_token=XXX&pretty=0&limit=25&after=MTI0ODM3NzE0NTI1NjY0MwZDZD"

I think the current version of the script doesn't support paging of the events (it does support paging of the venues thou). I think it can be handled in two ways - by adding paging support to update the events section of the venue in case it is pages or more simple way (yet less elegant) -> add a .limit(500) while querying for the events.

Best regards,
DP.

**Comment by tobilg** [comment]
Limits no longer work, and the code supports paging.
