### ISSUE TITLE
Can i use this?

### ISSUE THREAD

**Issue by sommmen** [tobilg/facebook-events-by-location-core#13]
Hi,

I need to fetch some events containing a keyword (eg. cars) inside a radius.
(i'd get events all over the world)
Google discover can do this quite smartly, but i still haven't seen another solution.

Is this - api heavy - hack the ONLY way to accomplish this still?
I'm guessing this is exactly as i need.

**Comment by tobilg** [comment]
This project is **only** for querying Facebook events. It supports the `query` parameter to search for specific events.

See https://github.com/tobilg/facebook-events-by-location-core#parameters
