### ISSUE TITLE
suggestion: cache events

### ISSUE THREAD

**Issue by sommmen** [tobilg/facebook-events-by-location-core#14]
Would be cool to stop rate limiting by caching the requests to /event/id in an SQLite db.

**Comment by tobilg** [comment]
Currently it is not planned to connect to a db. Eventually, I'll add Redis support at a later stage. But this would add a external dependency to the project, and add a lot of complexity to the application. So I'll close it for now.

Make sure that you use an appropriate access token to your requests.
