### ISSUE TITLE
Missing is_canceled field

### ISSUE THREAD

**Issue by kasarol** [tobilg/facebook-events-by-location-core#20]
I'm having an issue with events that have been canceled. I'm unable to reliably detect which events are canceled and would appreciate if you would add the is_canceled to the fields that are retrieved for an event (such a field is documented in https://developers.facebook.com/docs/graph-api/reference/event/).

**Comment by tobilg** [comment]
Thank you for the hint. I’ll include that in the next release. Stay tuned!

**Comment by tobilg** [comment]
This was fixed in version `0.7.0`, see 174d2fa5216a99befe039d12546bdb25d9534e5c

**Comment by kasarol** [comment]
Thanks, this should work! Could you also update facebook-events-by-location project to support passing this options?

**Comment by tobilg** [comment]
Yes, will try to release this today...

**Comment by tobilg** [comment]
I just release version `0.11.0` of [facebook-events-by-location](https://github.com/tobilg/facebook-events-by-location) (see https://github.com/tobilg/facebook-events-by-location/commit/2ee4950ee1d2fbe5caaab1fddd91a3ca82da6c6f)
