### ISSUE TITLE
Modification implicated by the API Graph v2.12

### ISSUE THREAD

**Issue by baudev** [tobilg/facebook-events-by-location-core#26]
Hi !

Concerning the last version of the API Graph v2.12, `is_draft` will require an admin token :[https://developers.facebook.com/docs/graph-api/changelog/version2.12#gapi-90](https://developers.facebook.com/docs/graph-api/changelog/version2.12#gapi-90)

Consequently, the `is_draft` variable should be removed otherwise it will provoke the following error :
```
(#200) Permissions error
```

**Comment by arjunlol** [comment]
I'm having the following error `{"message":"Request failed with status code 403","code":-1}` and thought maybe it was related to this?

**Comment by arjunlol** [comment]
Yup, removing the is_draft field seem to be the fix! PR - https://github.com/tobilg/facebook-events-by-location-core/pull/27

**Comment by tobilg** [comment]
This is fixed in version `0.10.1`, which was just published to npm. Closing.
