### ISSUE TITLE
Empty data at any coordinate

### ISSUE THREAD

**Issue by thecamarada** [tobilg/facebook-events-by-location-core#31]
Since a few days ago, no events is being found in any coordinate. As you can see, in this request:
```
{ data:
   { events: [],
     metadata: { venues: 168, venuesWithEvents: 0, events: 0 }
   }
}
```

I'm not sure if this lib needs an update or if the Facebook politics has changed. There is no error, no exceptions. Only empty results.

Has anyone noticed?

**Comment by tobilg** [comment]
There’s a lengthy discussion at https://github.com/tobilg/facebook-events-by-location-core/issues/29

This is caused by a change in FB‘s APIs.

**Comment by thecamarada** [comment]
Thanks for you answer, @tobilg.
