### ISSUE TITLE
Has Facebook discontinued event listing api for places?

### ISSUE THREAD

**Issue by lassegit** [tobilg/facebook-events-by-location-core#32]
I can't get this module to return events and I can't get Facebook's graph API to return either. As I [see Facebook](https://developers.facebook.com/docs/graph-api/reference/page/events/) has closed events listing down or limited it severely.

Is there anybody that can confirm this? 

*I wanted to make a simple event listing page where you could see local events in your city on a map without having to use Facebook directly.*

**Comment by bvarba** [comment]
Yes... you are not alone. i have been following the activity other people
have tried this... seems Facebook has disabled this api and currently no
known way to retrieve event listing. Hope some solution comes up...

**Comment by tobilg** [comment]
There a +100 comment discussion at #29, please have a look. Thanks.
