### ISSUE TITLE
Finding issues while trying to run the code using gulp test in terminal

### ISSUE THREAD

**Issue by srvrahul** [tobilg/facebook-events-by-location-core#33]
I find  two issues when trying to run 
In the self.allowedSorts array there is no wrongSortOption 
so   below condition is throwing error
 if (queryOptions.sort && self.allowedSorts.indexOf(queryOptions.sort) === -1) {
            
1)"error{\"message\":\"An invalid sort option was passed: 'wrongSortOption'\",\"code\":3}"

and also queryOptions.longitude I am getting a null value for longitude. 
2)The error is {"message":"Please specify the lat and lng parameters!","code":1}

**Comment by tobilg** [comment]
Not sure what you mean by 1). This error is raised if you specify a wrong sort option, see https://github.com/tobilg/facebook-events-by-location-core/blob/master/lib/eventSearch.js#L9

Regarding 2), the README makes it clear that the parameters are `lat` and `lng`: https://github.com/tobilg/facebook-events-by-location-core#parameters
