### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by znortr** [tobilg/facebook-events-by-location-core#5]
Hi there
I,m very intersted on this code, can you explain how to integrate it in a php file and how to retrieve the json output ? Or can I hire you for to do that? Thank's.

**Comment by tobilg** [comment]
You cannot integrate Node.js code in PHP. You could use the webservice from https://github.com/tobilg/facebook-events-by-location and call it from PHP, but that's something else.

Sorry, I'm not available for hire. Please stick to the docs provided.
