### ISSUE TITLE
Location of the Event

### ISSUE THREAD

**Issue by vrgomes** [tobilg/facebook-events-by-location-core#7]
Hi, I have found an issue with the location returned by facebook-events-by-location.

There are 2 locations on the Events of Facebook:
1- Location of the Page/Company that create the Event.
2- Location where the Event is going to occur.

The facebook-events-by-location is only looking for the number 1 and not for the 2 (where the event is really going to occur).
For instance, Travel Agency's have their headquarters is a location, but they create events everywhere in the country. If I search for the city where their headquarters is located, the facebook-events-by-location will show me all the events for all the country in locations far way from where I'm searching.
The facebook-events-by-location should look for the number 2 (Location where the event is goig to occur).

Example: https://www.facebook.com/events/1180548435392398
The facebook-events-by-location is returning this on "Coimbra, Portugal" where the headquarters of the company is located, but the event is going to happen on "Torres Novas, Portugal".

Is it possible to do this?

Greetings and thanks =)

**Comment by tobilg** [comment]
Please don't double-post issues, re https://github.com/tobilg/facebook-events-by-location/issues/17
